### ISSUE TITLE
Bug: `encoding` option in requestBody is not respected.

### ISSUE THREAD

**Issue by Thiry1** [Himenon/openapi-typescript-code-generator#104]
## Steps To Reproduce
According to the  [OpenAPI 3.0 definition](https://swagger.io/docs/specification/describing-request-body/#:~:text=The%20serialization%20strategy%20is%20specified%20in%20the%20encoding%20section), requestBody has `encoding` option.
However, the `encoding` option is missing from the generated code.

## The current behavior
`encoding` option is dissappear
## The expected behavior
`encoding` option should be respected.
IMO, if Content-Type is `application/x-www-form-urlencoded`, `encoding` option is required for the type of `requestBody`.

**Comment by Thiry1** [comment]
>Should I make the argument an object if I expect to add more in the future?

IMO, accepting object as an argument is a good choice.
However this causes breaking change.So I think we have to bump major version.(It would be better to have version 1.0.0 before making this change.)

**Comment by hrsh7th** [comment]
I also agree this. I think it's a common best practice to keep public API arguments defines as dict.

**Comment by Himenon** [comment]
you can check in playground v0,25.0

https://openapi-typescript-code-generator.netlify.app/v0.25.0/index.html
