### ISSUE TITLE
Bug: `paths` like `/foo/{id}.json` does not work

### ISSUE THREAD

**Issue by leader22** [Himenon/openapi-typescript-code-generator#111]
## Steps To Reproduce

For example,

```yaml
openapi: 3.1.0
info:
  version: 1.0.0
  title: ref.access
  description: Library test schema
  license:
    name: MIT

components:
  schemas:
    Book:
      type: object
      properties:
        name:
          type: string

paths:
  # 🈁 
  /book/{id}.json:
    parameters:
      - name: id
        in: path
        required: true
        description: Book ID
        schema:
          type: string
          format: uuid
    get:
      operationId: getBook
      responses:
        200:
          description: Get Books
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
  
```

Paste this spec at https://openapi-typescript-code-generator.netlify.app/v0.26.0/index.html 

## The current behavior

![image](https://github.com/Himenon/openapi-typescript-code-generator/assets/6259812/73e01292-2339-450c-8370-561fb5d15989)

`/book/${params.parameter.id}/.json` is invalid path.

## The expected behavior

It should be `/book/${params.parameter.id}.json`.

**Comment by Himenon** [comment]
Thanks for the report. I will check it out.

**Comment by leader22** [comment]
So quick! Thank you so much! 👍🏻

**Comment by Himenon** [comment]
v0.27.1 fixed!

![image](https://github.com/Himenon/openapi-typescript-code-generator/assets/6715229/36c703a2-d8a3-4950-84b2-c2215480b071)
