### ISSUE TITLE
Feature Request:  adapt name includes parentheses string

### ISSUE THREAD

**Issue by tkow** [Himenon/openapi-typescript-code-generator#125]
## Steps To Reproduce

Run `bun i && bun gen.ts` in https://github.com/tkow/cloudflare-ts-client.

This spec includes parentheses in operationId , which is valid though It's not recommended in [OAS 3.0.3](https://spec.openapis.org/oas/v3.0.3#fixed-fields-7).
operationId: secondary-dns-(-primary-zone)-create-primary-zone-configuration
 

## The current behavior
See generated codes from a coudflare spec.
https://github.com/tkow/cloudflare-ts-client/blob/main/src/client.ts

## The expected behavior

Sanitize them to valid function name.

**Comment by Himenon** [comment]
@tkow  Thanks for the report!

This problem has been fixed in [v1.0.5](https://github.com/Himenon/openapi-typescript-code-generator/releases/tag/%40himenon%2Fopenapi-typescript-code-generator%401.0.5).
