### ISSUE TITLE
Bug: path parameter should be encoded

### ISSUE THREAD

**Issue by Thiry1** [Himenon/openapi-typescript-code-generator#131]
Because the path parameters are not encoded, passing values containing '/' or '?' will result in the destination path becoming unintended. I guess we shoulld encode the path parameters using encodeURIComponent.

## Steps To Reproduce
```typescript
// generated code
export const createClient = <RequestOption>(apiClient: ApiClient<RequestOption>, baseUrl: string) => {
    const _baseUrl = baseUrl.replace(/\/$/, "");
    return {
        getBook: (params: Params$getBook, option?: RequestOption): Promise<Response$getBook$Status$200["application/json"]> => {
            const url = _baseUrl + `/get/book/${params.parameter.id}`;
            const headers = {
                Accept: "application/json"
            };
            return apiClient.request({
                httpMethod: "GET",
                url,
                headers
            }, option);
        },
    }
}
```

```typescript
const client = createClient(something);
client.getBook({
  params: {
    parameter: {
      id: "foo/bar" // params contains `/`
    },
  }
})
```

## The current behavior
request to /get/book/foo/bar
## The expected behavior
request to /get/book/foo%2Fbar

**Comment by Himenon** [comment]
@Thiry1 

Thanks for the bug report! I checked the Document and found that this is a responsibility that should be held on the generated code side.

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#path-templating

**Comment by Thiry1** [comment]
Thank you for the quick fix!
