### ISSUE TITLE
Bug: component schemas cannot be in random order

### ISSUE THREAD

**Issue by KoharaKazuya** [Himenon/openapi-typescript-code-generator#7]
## Steps To Reproduce

The following is a valid OpenAPI document. In openapi-typescript-code-generator, however, build error occurs.
([demo in the playground](https://himenon.github.io/openapi-typescript-code-generator-playground/index.html?code=FAewDgpgdghmCWAuABAZgHQAZ2uPKAZiIsMsgC7zkA2EKAJhALYinIBuEATgM7whQUARixZgYGOQAWPFAG8AvsGABjEEzADo5WWx4qpzGLrJkAwgJ4BXJtxKnT5AJ6QUIAEYArCCvJsHYFzg3JQQJg6mgSDs8Ixc9hEOACRcEAQoAOQAxAD0ahpaUDo5%2BoZMxjkACkExcRn%2ByNXRsXYNZM6uyPjkEADm3EA))

```yaml
openapi: 3.0.3
info:
  title: demo
  version: 1.0.0
paths: {}

components:
  schemas:
    Consumer:
      type: object
      properties:
        provider:
          $ref: '#/components/schemas/Provider'
    Provider:
      type: integer
```

## The current behavior

Build error occurs.

## The expected behavior

We don't need to care order.

**Comment by Himenon** [comment]
@KoharaKazuya 
Thank you! This fix is ​​over.
