### ISSUE TITLE
Bug: DevelopmentError

### ISSUE THREAD

**Issue by hi-se** [Himenon/openapi-typescript-code-generator#89]
## Steps To Reproduce

1. copy [this api definition](https://app.swaggerhub.com/apis/CloudSign/cloudsign-web_api/0.19.1) and paste it in `specs/test.yaml`
2. copy [sample generator code](https://github.com/Himenon/openapi-typescript-code-generator/blob/main/docs/ja/README-ja.md#%E5%9E%8B%E5%AE%9A%E7%BE%A9%E3%81%AE%E3%81%BF%E3%81%AE%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B) and paste it in `src/generator.ts`
3. replace path in `src/generator.ts`
4. execute `ts-node src/generator.ts`

## The current behavior

This error occured.

```
DevelopmentError: This is an implementation error. Please report any reproducible information below.
https://github.com/Himenon/openapi-typescript-code-generator/issues/new/choose

    at resolveLocalReference (/workspace/node_modules/@himenon/src/internal/ResolveReference/index.ts:95:15)
    at /workspace/node_modules/@himenon/src/internal/ResolveReference/index.ts:111:18
    at Array.forEach (<anonymous>)
    at resolveLocalReference (/workspace/node_modules/@himenon/src/internal/ResolveReference/index.ts:110:25)
    at /workspace/node_modules/@himenon/src/internal/ResolveReference/index.ts:111:18
    at Array.forEach (<anonymous>)
    at resolveLocalReference (/workspace/node_modules/@himenon/src/internal/ResolveReference/index.ts:110:25)
    at /workspace/node_modules/@himenon/src/internal/ResolveReference/index.ts:111:18
    at Array.forEach (<anonymous>)
    at resolveLocalReference (/workspace/node_modules/@himenon/src/internal/ResolveReference/index.ts:110:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

Same issue occurred for [this api definition](https://docs.jumpcloud.com/api/1.0/index.html).

**Comment by Himenon** [comment]
I'll check it

**Comment by Himenon** [comment]
Currently, the following alias pattern do not appear to be implemented We will check to see if they can be supported.

```
"$ref: #/paths/~1token/post/responses/200"
```

And, I have confirmed that it works by creating an alias for the `components/responses` field as follows.

```yaml
posts:
  /token:
    get:
      # ....
      responses:
        "200":
          $ref: "#/components/responses/Success200"

components:
  responses:
    Success200:
      description: 正常時
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/accessTokenModel"
```

LIke this: https://github.com/Himenon/openapi-typescript-code-generator/blob/main/test/api.test.domain/index.yml#L306-L311

**Comment by hi-se** [comment]
Thank you for your reply!

I followed your example and was able to resolve the error.

Thanks!
