### ISSUE TITLE
Bug: definitions/any requires type:object

### ISSUE THREAD

**Issue by ytoune** [Himenon/openapi-typescript-code-generator#9]
## Steps To Reproduce

```yml
openapi: 3.0.0
info:
  version: 1.0.0
  title: DEMO
components:
  schemas:
    Author:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: number
          example: 12 # error
        name:
          type: string
          example: { value: hoge } # no error
paths: {}
```

https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml#L323

## The current behavior

validation errors happen.

## The expected behavior

no errors.

thank you.

**Comment by Himenon** [comment]
@ytoune 
Thanks for the bug report. It's been fixed in version 0.1.6!
