### ISSUE TITLE
Do you have the plan to suppor tree-shaking?

### ISSUE THREAD

**Issue by hrsh7th** [Himenon/openapi-typescript-code-generator#97]
I'm experimenting this code generator. It's functionality is meet to my use-case.

However, I have one problem to use this. The generated code is big one class so if I try to use one of the API in the client, then all api's are bundled.

Do you have the plan to improve this?

**Comment by Himenon** [comment]
```tsx
import { CodeGenerator } from "@himenon/openapi-typescript-code-generator";
```

has an option ``allowOperationIds``. This allows you to specify only the `operationId` you want to use!


Like this:

```tsx
 const codeGenerator = new CodeGenerator(entryPoint, {
    convertOption: {},
    allowOperationIds: [
      "git/get-ref",
      "git/create-ref",
      "git/create-blob",
      "git/create-tree",
      "git/create-commit",
      "git/get-tree",
      "git/update-ref",
      "repos/get",
      "repos/get-commit",
      "repos/list-branches",
      "repos/list-tags",
    ],
  });
```

https://github.com/Himenon/github-api-create-commit/blob/9dfb81f1286f40e02db4f6c6825b4393b185a649/scripts/generateTsCode.ts#LL23

**Comment by hrsh7th** [comment]
oh. Thank you for your quick response.
However, I don't mean to rush you.
You can consider it at your own pace :)

**Comment by Himenon** [comment]
Functional Api Client is now available in v0.22.0. Please try it out!

https://github.com/Himenon/openapi-typescript-code-generator/releases/tag/%40himenon%2Fopenapi-typescript-code-generator%400.22.0


@hrsh7th

**Comment by hrsh7th** [comment]
Thank you for your very quick work!

Hm... I don't know that the bundlers supports tree-shaking if the module has `module scoped variable` and the exported functions uses it.

The member of my team who was assigned to use this is on vacation.
So I will late report experimenting new feature. Sorry.

**Comment by Himenon** [comment]
If you know the cause of this, please let me know. We'll work on it as long as it can be remedied!

**Comment by Thiry1** [comment]
I tried this with the [Terser REPL](https://try.terser.org/).

Following code that generated by v0.22.0 is not suppport tree sharking.
```js
export const createClient = (apiClient, baseUrl) => {
    const _baseUrl = baseUrl.replace(/\/$/, "");
    return {
        getBooks: (option) => {
            const url = _baseUrl + `/get/books`;
            const headers = {};
            return apiClient.request("GET", url, headers, undefined, undefined, option);
        },
        searchBooks: (params, optionn) => {
            const url = _baseUrl + `/search/books`;
            const headers = {
                Accept: "application/json"
            };
            const queryParameters = {
                filter: { value: params.parameter.filter, style: "deepObject", explode: true }
            };
            return apiClient.request("GET", url, headers, undefined, queryParameters, option);
        }
    };
};

const client = createClient({}, "");
client.getBooks();
```
Terser outputs:
```js
export const createClient=(e,o)=>{const t=o.replace(/\/$/,"");return{getBooks:o=>{const r=t+"/get/books";return e.request("GET",r,{},void 0,void 0,o)},searchBooks:(o,r)=>{const s=t+"/search/books",c={filter:{value:o.parameter.filter,style:"deepObject",explode:!0}};return e.request("GET",s,{Accept:"application/json"},void 0,c,option)}}};createClient({},"").getBooks();
```

The following codes are supports tree shaking, although the interface is subtle.
```js
const client = {
  getBooks: (apiClient, option) => {
    const url = _baseUrl + `/get/books`;
    const headers = {};
    return apiClient.request("GET", url, headers, undefined, undefined, option);
  },
  searchBooks: (apiClient, params, optionn) => {
  	const url = _baseUrl + `/search/books`;
    const headers = {
      Accept: "application/json"
    };
    const queryParameters = {
      filter: { value: params.parameter.filter, style: "deepObject", explode: true }
    };
    return apiClient.request("GET", url, headers, undefined, queryParameters, option);
  }
};
client.getBooks()
```
Terser outputs:
```js
((o,e)=>{const s=_baseUrl+"/get/books";o.request("GET",s,{},void 0,void 0,e)})();
```

**Comment by hrsh7th** [comment]
At least, the accepting `apiClient` via argument is meet to my use case.

Because my team would use the api-client with the following way.

```ts
invoke(generatedApiFunc, ...);
```

In this way, the `apiClient` argument would be filled by `invoke` function.

But I can understand that the developer dislike adding the non-meaningful argument to API interface.

**Comment by hrsh7th** [comment]
I submitted the PR that improves the tree-shaking support.
H
owever, in that PR the implementation that constructs the URL is broken.
I don't know the cause. . . Probably the only blocker. Any advice would be appreciated.

**Comment by Thiry1** [comment]
@hrsh7th How about this?Following code will be generated.
https://github.com/hrsh7th/openapi-typescript-code-generator/compare/main...Thiry1:openapi-typescript-code-generator:feat/add-base-url

```typescript
export const getBooks = <RequestOption>(apiClient: ApiClient<RequestOption>, baseUrl: string, option?: RequestOption): Promise<Response$getBooks$Status$200["application/json"]> => {
    const url = baseUrl.replace(/\/$/, "") + `/get/books`;
    const headers = {
        Accept: "application/json"
    };
    return apiClient.request("GET", url, headers, undefined, undefined, option);
};
export const searchBooks = <RequestOption>(apiClient: ApiClient<RequestOption>, baseUrl: string, params: Params$searchBooks, option?: RequestOption): Promise<Response$searchBooks$Status$200["application/json"]> => {
    const url = baseUrl.replace(/\/$/, "") + `/search/books`;
    const headers = {
        Accept: "application/json"
    };
    const queryParameters: QueryParameters = {
        filter: { value: params.parameter.filter, style: "deepObject", explode: true }
    };
    return apiClient.request("GET", url, headers, undefined, queryParameters, option);
};
```

**Comment by hrsh7th** [comment]
I see. I was thinking that apiClient should process the URL.
Certainly, there seems to be no problem with receiving it as an argument.
It seems to be close to the original implementation.
_google translated_

**Comment by Himenon** [comment]
Oops, sorry, there seems to be an implementation omission in `FunctionalApiClient` in the main branch. Specifically, we need to use the following `getTemplateSpan` to assemble URLs properly.

https://github.com/Himenon/openapi-typescript-code-generator/blob/main/src/code-templates/class-api-client/utils.ts#L20

![image](https://user-images.githubusercontent.com/6715229/228485988-7affc94d-5e41-44ba-b3da-558e111ebbe6.png)


Unless this is resolved, it will be difficult to issue a PR. Sorry.

I understood the direction from #97 and #103 to at least implement Tree-shaking.

Various bugs and other things need to be fixed, so please wait a little. I will fix it in the not too distant future.

**Comment by Himenon** [comment]
[v0.26.0](https://github.com/Himenon/openapi-typescript-code-generator/releases/tag/%40himenon%2Fopenapi-typescript-code-generator%400.26.0) has been released, and you can check various Templates in the Playground.

https://openapi-typescript-code-generator.netlify.app/v0.26.0/index.html

![aaa](https://user-images.githubusercontent.com/6715229/229328415-d0775a31-e1a0-42ec-8aa9-837c4312e2b7.png)

**Comment by hrsh7th** [comment]
It seems perfect to me. Thank you a lot!
